version: "2"
checks:
    argument-count:
        enabled: true
        config:
            threshold: 5
exclude_patterns:
    - "src/Telegram/Endpoints/"
    - "src/Telegram/Types/"
    - "tests"
    - "vendor"
