title: Nutgram
description: The Telegram bot library that doesn't drive you nuts

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true
  
exclude:
  - Gemfile
  - Gemfile.lock